---

crio_packages:
  - "cri-o"
  - "cri-o-runc"

# The crio_runtimes variable defines a list of OCI compatible runtimes.
crio_runtimes:
  - name: runc
    path: /usr/sbin/runc
    type: oci
    root: /run/runc
